# Generated by Django 2.2.6 on 2019-12-02 23:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blob_path', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
