# Generated by Django 2.2.6 on 2019-10-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_auto_20191006_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.CharField(default='Введите описание стрима', max_length=255),
        ),
    ]
