# Generated by Django 2.2.6 on 2019-10-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_stream_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
