# Generated by Django 2.2.6 on 2019-10-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_stream_viewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='name',
        ),
    ]
