# Generated by Django 2.2.6 on 2019-10-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_remove_stream_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
    ]
