# Generated by Django 2.2.8 on 2019-12-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0006_chunk_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='prob',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=5),
        ),
    ]
