# Generated by Django 2.2.9 on 2020-03-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0008_auto_20200223_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
