FROM python:3.8.1-slim-buster

COPY . /usr/src/backend
WORKDIR /usr/src/backend

ENV PIP_DEFAULT_TIMEOUT 1000
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip && \
    pip install pipenv && \
    pipenv install --system

CMD ./run.sh
