# Generated by Django 2.2.6 on 2019-10-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191012_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'unique_err'}, max_length=254, unique=True),
        ),
    ]
