# Generated by Django 2.2.6 on 2019-10-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191014_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
