# Generated by Django 2.2.6 on 2019-10-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_viewers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stream_name',
            new_name='stream_description',
        ),
    ]
