# Generated by Django 2.2.6 on 2019-10-14 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_remove_stream_name'),
        ('users', '0008_auto_20191014_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='user',
            name='viewers',
        ),
        migrations.AddField(
            model_name='user',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='streams.Stream'),
        ),
    ]
