# Generated by Django 2.2.6 on 2019-10-17 20:20

from django.db import migrations, models
import users.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191014_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_color',
            field=models.CharField(default=users.models.user.get_random_color, max_length=255),
        ),
    ]
