# Generated by Django 2.2.6 on 2019-10-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191018_1928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'channel')},
        ),
    ]
